
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  QuizAttempt: 'QuizAttempt',
  QuestionAttempt: 'QuestionAttempt',
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Module: 'Module',
  ModuleEnrollment: 'ModuleEnrollment',
  Chapter: 'Chapter',
  Topic: 'Topic',
  Assignment_Attempt: 'Assignment_Attempt',
  Question: 'Question',
  Answer: 'Answer',
  UserAnswer: 'UserAnswer',
  Flashcard: 'Flashcard',
  Timetable: 'Timetable',
  Notification: 'Notification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const QuizAttemptScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  topicId: 'topicId',
  moduleId: 'moduleId',
  totalQuestions: 'totalQuestions',
  questionsData: 'questionsData',
  settings: 'settings',
  status: 'status',
  score: 'score',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type QuizAttemptScalarFieldEnum = (typeof QuizAttemptScalarFieldEnum)[keyof typeof QuizAttemptScalarFieldEnum]


export const QuestionAttemptScalarFieldEnum = {
  id: 'id',
  quizAttemptId: 'quizAttemptId',
  questionId: 'questionId',
  selectedAnswerId: 'selectedAnswerId',
  isCorrect: 'isCorrect',
  order: 'order',
  status: 'status',
  answeredAt: 'answeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type QuestionAttemptScalarFieldEnum = (typeof QuestionAttemptScalarFieldEnum)[keyof typeof QuestionAttemptScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  password: 'password',
  role: 'role',
  streakDays: 'streakDays',
  lastVisitDate: 'lastVisitDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const ModuleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  createdAt: 'createdAt'
} as const

export type ModuleScalarFieldEnum = (typeof ModuleScalarFieldEnum)[keyof typeof ModuleScalarFieldEnum]


export const ModuleEnrollmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  moduleId: 'moduleId',
  enrolledAt: 'enrolledAt'
} as const

export type ModuleEnrollmentScalarFieldEnum = (typeof ModuleEnrollmentScalarFieldEnum)[keyof typeof ModuleEnrollmentScalarFieldEnum]


export const ChapterScalarFieldEnum = {
  id: 'id',
  moduleId: 'moduleId',
  title: 'title',
  order: 'order',
  createdAt: 'createdAt'
} as const

export type ChapterScalarFieldEnum = (typeof ChapterScalarFieldEnum)[keyof typeof ChapterScalarFieldEnum]


export const TopicScalarFieldEnum = {
  id: 'id',
  chapterId: 'chapterId',
  title: 'title',
  content: 'content',
  order: 'order',
  createdAt: 'createdAt',
  assignment: 'assignment'
} as const

export type TopicScalarFieldEnum = (typeof TopicScalarFieldEnum)[keyof typeof TopicScalarFieldEnum]


export const Assignment_AttemptScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  userId: 'userId',
  percentage: 'percentage',
  passed: 'passed',
  createdAt: 'createdAt'
} as const

export type Assignment_AttemptScalarFieldEnum = (typeof Assignment_AttemptScalarFieldEnum)[keyof typeof Assignment_AttemptScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  question: 'question',
  difficulty: 'difficulty',
  createdAt: 'createdAt'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const AnswerScalarFieldEnum = {
  id: 'id',
  questionId: 'questionId',
  answer: 'answer',
  isCorrect: 'isCorrect'
} as const

export type AnswerScalarFieldEnum = (typeof AnswerScalarFieldEnum)[keyof typeof AnswerScalarFieldEnum]


export const UserAnswerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  questionId: 'questionId',
  selectedAnswerId: 'selectedAnswerId',
  isCorrect: 'isCorrect',
  answeredAt: 'answeredAt'
} as const

export type UserAnswerScalarFieldEnum = (typeof UserAnswerScalarFieldEnum)[keyof typeof UserAnswerScalarFieldEnum]


export const FlashcardScalarFieldEnum = {
  id: 'id',
  topicId: 'topicId',
  front: 'front',
  back: 'back',
  createdAt: 'createdAt'
} as const

export type FlashcardScalarFieldEnum = (typeof FlashcardScalarFieldEnum)[keyof typeof FlashcardScalarFieldEnum]


export const TimetableScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  moduleId: 'moduleId',
  assignmentTitle: 'assignmentTitle',
  startDate: 'startDate',
  dueDate: 'dueDate',
  chaptersPlanned: 'chaptersPlanned',
  chaptersCompleted: 'chaptersCompleted'
} as const

export type TimetableScalarFieldEnum = (typeof TimetableScalarFieldEnum)[keyof typeof TimetableScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  scheduledAt: 'scheduledAt',
  isSent: 'isSent'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

