
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Module
 * 
 */
export type Module = Prisma.ModuleModel
/**
 * Model ModuleEnrollment
 * 
 */
export type ModuleEnrollment = Prisma.ModuleEnrollmentModel
/**
 * Model Chapter
 * 
 */
export type Chapter = Prisma.ChapterModel
/**
 * Model Topic
 * 
 */
export type Topic = Prisma.TopicModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model Answer
 * 
 */
export type Answer = Prisma.AnswerModel
/**
 * Model UserAnswer
 * 
 */
export type UserAnswer = Prisma.UserAnswerModel
/**
 * Model Flashcard
 * 
 */
export type Flashcard = Prisma.FlashcardModel
/**
 * Model Timetable
 * 
 */
export type Timetable = Prisma.TimetableModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
