
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const QuizStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  ABANDONED: 'ABANDONED'
} as const

export type QuizStatus = (typeof QuizStatus)[keyof typeof QuizStatus]


export const AnswerStatus = {
  PENDING: 'PENDING',
  ANSWERED: 'ANSWERED',
  SKIPPED: 'SKIPPED',
  REVIEWING: 'REVIEWING'
} as const

export type AnswerStatus = (typeof AnswerStatus)[keyof typeof AnswerStatus]
