
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Assignment_Attempt` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Assignment_Attempt
 * 
 */
export type Assignment_AttemptModel = runtime.Types.Result.DefaultSelection<Prisma.$Assignment_AttemptPayload>

export type AggregateAssignment_Attempt = {
  _count: Assignment_AttemptCountAggregateOutputType | null
  _avg: Assignment_AttemptAvgAggregateOutputType | null
  _sum: Assignment_AttemptSumAggregateOutputType | null
  _min: Assignment_AttemptMinAggregateOutputType | null
  _max: Assignment_AttemptMaxAggregateOutputType | null
}

export type Assignment_AttemptAvgAggregateOutputType = {
  percentage: number | null
}

export type Assignment_AttemptSumAggregateOutputType = {
  percentage: number | null
}

export type Assignment_AttemptMinAggregateOutputType = {
  id: string | null
  topicId: string | null
  userId: string | null
  percentage: number | null
  passed: boolean | null
  createdAt: Date | null
}

export type Assignment_AttemptMaxAggregateOutputType = {
  id: string | null
  topicId: string | null
  userId: string | null
  percentage: number | null
  passed: boolean | null
  createdAt: Date | null
}

export type Assignment_AttemptCountAggregateOutputType = {
  id: number
  topicId: number
  userId: number
  percentage: number
  passed: number
  createdAt: number
  _all: number
}


export type Assignment_AttemptAvgAggregateInputType = {
  percentage?: true
}

export type Assignment_AttemptSumAggregateInputType = {
  percentage?: true
}

export type Assignment_AttemptMinAggregateInputType = {
  id?: true
  topicId?: true
  userId?: true
  percentage?: true
  passed?: true
  createdAt?: true
}

export type Assignment_AttemptMaxAggregateInputType = {
  id?: true
  topicId?: true
  userId?: true
  percentage?: true
  passed?: true
  createdAt?: true
}

export type Assignment_AttemptCountAggregateInputType = {
  id?: true
  topicId?: true
  userId?: true
  percentage?: true
  passed?: true
  createdAt?: true
  _all?: true
}

export type Assignment_AttemptAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assignment_Attempt to aggregate.
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assignment_Attempts to fetch.
   */
  orderBy?: Prisma.Assignment_AttemptOrderByWithRelationInput | Prisma.Assignment_AttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Assignment_AttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assignment_Attempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assignment_Attempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Assignment_Attempts
  **/
  _count?: true | Assignment_AttemptCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Assignment_AttemptAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Assignment_AttemptSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Assignment_AttemptMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Assignment_AttemptMaxAggregateInputType
}

export type GetAssignment_AttemptAggregateType<T extends Assignment_AttemptAggregateArgs> = {
      [P in keyof T & keyof AggregateAssignment_Attempt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssignment_Attempt[P]>
    : Prisma.GetScalarType<T[P], AggregateAssignment_Attempt[P]>
}




export type Assignment_AttemptGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Assignment_AttemptWhereInput
  orderBy?: Prisma.Assignment_AttemptOrderByWithAggregationInput | Prisma.Assignment_AttemptOrderByWithAggregationInput[]
  by: Prisma.Assignment_AttemptScalarFieldEnum[] | Prisma.Assignment_AttemptScalarFieldEnum
  having?: Prisma.Assignment_AttemptScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Assignment_AttemptCountAggregateInputType | true
  _avg?: Assignment_AttemptAvgAggregateInputType
  _sum?: Assignment_AttemptSumAggregateInputType
  _min?: Assignment_AttemptMinAggregateInputType
  _max?: Assignment_AttemptMaxAggregateInputType
}

export type Assignment_AttemptGroupByOutputType = {
  id: string
  topicId: string
  userId: string
  percentage: number
  passed: boolean
  createdAt: Date
  _count: Assignment_AttemptCountAggregateOutputType | null
  _avg: Assignment_AttemptAvgAggregateOutputType | null
  _sum: Assignment_AttemptSumAggregateOutputType | null
  _min: Assignment_AttemptMinAggregateOutputType | null
  _max: Assignment_AttemptMaxAggregateOutputType | null
}

export type GetAssignment_AttemptGroupByPayload<T extends Assignment_AttemptGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Assignment_AttemptGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Assignment_AttemptGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Assignment_AttemptGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Assignment_AttemptGroupByOutputType[P]>
      }
    >
  >



export type Assignment_AttemptWhereInput = {
  AND?: Prisma.Assignment_AttemptWhereInput | Prisma.Assignment_AttemptWhereInput[]
  OR?: Prisma.Assignment_AttemptWhereInput[]
  NOT?: Prisma.Assignment_AttemptWhereInput | Prisma.Assignment_AttemptWhereInput[]
  id?: Prisma.StringFilter<"Assignment_Attempt"> | string
  topicId?: Prisma.StringFilter<"Assignment_Attempt"> | string
  userId?: Prisma.StringFilter<"Assignment_Attempt"> | string
  percentage?: Prisma.IntFilter<"Assignment_Attempt"> | number
  passed?: Prisma.BoolFilter<"Assignment_Attempt"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Assignment_Attempt"> | Date | string
}

export type Assignment_AttemptOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Assignment_AttemptWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.Assignment_AttemptWhereInput | Prisma.Assignment_AttemptWhereInput[]
  OR?: Prisma.Assignment_AttemptWhereInput[]
  NOT?: Prisma.Assignment_AttemptWhereInput | Prisma.Assignment_AttemptWhereInput[]
  topicId?: Prisma.StringFilter<"Assignment_Attempt"> | string
  userId?: Prisma.StringFilter<"Assignment_Attempt"> | string
  percentage?: Prisma.IntFilter<"Assignment_Attempt"> | number
  passed?: Prisma.BoolFilter<"Assignment_Attempt"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Assignment_Attempt"> | Date | string
}, "id">

export type Assignment_AttemptOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.Assignment_AttemptCountOrderByAggregateInput
  _avg?: Prisma.Assignment_AttemptAvgOrderByAggregateInput
  _max?: Prisma.Assignment_AttemptMaxOrderByAggregateInput
  _min?: Prisma.Assignment_AttemptMinOrderByAggregateInput
  _sum?: Prisma.Assignment_AttemptSumOrderByAggregateInput
}

export type Assignment_AttemptScalarWhereWithAggregatesInput = {
  AND?: Prisma.Assignment_AttemptScalarWhereWithAggregatesInput | Prisma.Assignment_AttemptScalarWhereWithAggregatesInput[]
  OR?: Prisma.Assignment_AttemptScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Assignment_AttemptScalarWhereWithAggregatesInput | Prisma.Assignment_AttemptScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Assignment_Attempt"> | string
  topicId?: Prisma.StringWithAggregatesFilter<"Assignment_Attempt"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Assignment_Attempt"> | string
  percentage?: Prisma.IntWithAggregatesFilter<"Assignment_Attempt"> | number
  passed?: Prisma.BoolWithAggregatesFilter<"Assignment_Attempt"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Assignment_Attempt"> | Date | string
}

export type Assignment_AttemptCreateInput = {
  id?: string
  topicId: string
  userId: string
  percentage: number
  passed: boolean
  createdAt?: Date | string
}

export type Assignment_AttemptUncheckedCreateInput = {
  id?: string
  topicId: string
  userId: string
  percentage: number
  passed: boolean
  createdAt?: Date | string
}

export type Assignment_AttemptUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  percentage?: Prisma.IntFieldUpdateOperationsInput | number
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Assignment_AttemptUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  percentage?: Prisma.IntFieldUpdateOperationsInput | number
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Assignment_AttemptCreateManyInput = {
  id?: string
  topicId: string
  userId: string
  percentage: number
  passed: boolean
  createdAt?: Date | string
}

export type Assignment_AttemptUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  percentage?: Prisma.IntFieldUpdateOperationsInput | number
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Assignment_AttemptUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  percentage?: Prisma.IntFieldUpdateOperationsInput | number
  passed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Assignment_AttemptCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Assignment_AttemptAvgOrderByAggregateInput = {
  percentage?: Prisma.SortOrder
}

export type Assignment_AttemptMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Assignment_AttemptMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  percentage?: Prisma.SortOrder
  passed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type Assignment_AttemptSumOrderByAggregateInput = {
  percentage?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type Assignment_AttemptSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topicId?: boolean
  userId?: boolean
  percentage?: boolean
  passed?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["assignment_Attempt"]>

export type Assignment_AttemptSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topicId?: boolean
  userId?: boolean
  percentage?: boolean
  passed?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["assignment_Attempt"]>

export type Assignment_AttemptSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topicId?: boolean
  userId?: boolean
  percentage?: boolean
  passed?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["assignment_Attempt"]>

export type Assignment_AttemptSelectScalar = {
  id?: boolean
  topicId?: boolean
  userId?: boolean
  percentage?: boolean
  passed?: boolean
  createdAt?: boolean
}

export type Assignment_AttemptOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "topicId" | "userId" | "percentage" | "passed" | "createdAt", ExtArgs["result"]["assignment_Attempt"]>

export type $Assignment_AttemptPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Assignment_Attempt"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    topicId: string
    userId: string
    percentage: number
    passed: boolean
    createdAt: Date
  }, ExtArgs["result"]["assignment_Attempt"]>
  composites: {}
}

export type Assignment_AttemptGetPayload<S extends boolean | null | undefined | Assignment_AttemptDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload, S>

export type Assignment_AttemptCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Assignment_AttemptFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Assignment_AttemptCountAggregateInputType | true
  }

export interface Assignment_AttemptDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Assignment_Attempt'], meta: { name: 'Assignment_Attempt' } }
  /**
   * Find zero or one Assignment_Attempt that matches the filter.
   * @param {Assignment_AttemptFindUniqueArgs} args - Arguments to find a Assignment_Attempt
   * @example
   * // Get one Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Assignment_AttemptFindUniqueArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Assignment_Attempt that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Assignment_AttemptFindUniqueOrThrowArgs} args - Arguments to find a Assignment_Attempt
   * @example
   * // Get one Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Assignment_AttemptFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assignment_Attempt that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptFindFirstArgs} args - Arguments to find a Assignment_Attempt
   * @example
   * // Get one Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Assignment_AttemptFindFirstArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptFindFirstArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assignment_Attempt that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptFindFirstOrThrowArgs} args - Arguments to find a Assignment_Attempt
   * @example
   * // Get one Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Assignment_AttemptFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Assignment_Attempts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Assignment_Attempts
   * const assignment_Attempts = await prisma.assignment_Attempt.findMany()
   * 
   * // Get first 10 Assignment_Attempts
   * const assignment_Attempts = await prisma.assignment_Attempt.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assignment_AttemptWithIdOnly = await prisma.assignment_Attempt.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Assignment_AttemptFindManyArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Assignment_Attempt.
   * @param {Assignment_AttemptCreateArgs} args - Arguments to create a Assignment_Attempt.
   * @example
   * // Create one Assignment_Attempt
   * const Assignment_Attempt = await prisma.assignment_Attempt.create({
   *   data: {
   *     // ... data to create a Assignment_Attempt
   *   }
   * })
   * 
   */
  create<T extends Assignment_AttemptCreateArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptCreateArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Assignment_Attempts.
   * @param {Assignment_AttemptCreateManyArgs} args - Arguments to create many Assignment_Attempts.
   * @example
   * // Create many Assignment_Attempts
   * const assignment_Attempt = await prisma.assignment_Attempt.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Assignment_AttemptCreateManyArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Assignment_Attempts and returns the data saved in the database.
   * @param {Assignment_AttemptCreateManyAndReturnArgs} args - Arguments to create many Assignment_Attempts.
   * @example
   * // Create many Assignment_Attempts
   * const assignment_Attempt = await prisma.assignment_Attempt.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Assignment_Attempts and only return the `id`
   * const assignment_AttemptWithIdOnly = await prisma.assignment_Attempt.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Assignment_AttemptCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Assignment_Attempt.
   * @param {Assignment_AttemptDeleteArgs} args - Arguments to delete one Assignment_Attempt.
   * @example
   * // Delete one Assignment_Attempt
   * const Assignment_Attempt = await prisma.assignment_Attempt.delete({
   *   where: {
   *     // ... filter to delete one Assignment_Attempt
   *   }
   * })
   * 
   */
  delete<T extends Assignment_AttemptDeleteArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptDeleteArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Assignment_Attempt.
   * @param {Assignment_AttemptUpdateArgs} args - Arguments to update one Assignment_Attempt.
   * @example
   * // Update one Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Assignment_AttemptUpdateArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptUpdateArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Assignment_Attempts.
   * @param {Assignment_AttemptDeleteManyArgs} args - Arguments to filter Assignment_Attempts to delete.
   * @example
   * // Delete a few Assignment_Attempts
   * const { count } = await prisma.assignment_Attempt.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Assignment_AttemptDeleteManyArgs>(args?: Prisma.SelectSubset<T, Assignment_AttemptDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assignment_Attempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Assignment_Attempts
   * const assignment_Attempt = await prisma.assignment_Attempt.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Assignment_AttemptUpdateManyArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assignment_Attempts and returns the data updated in the database.
   * @param {Assignment_AttemptUpdateManyAndReturnArgs} args - Arguments to update many Assignment_Attempts.
   * @example
   * // Update many Assignment_Attempts
   * const assignment_Attempt = await prisma.assignment_Attempt.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Assignment_Attempts and only return the `id`
   * const assignment_AttemptWithIdOnly = await prisma.assignment_Attempt.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Assignment_AttemptUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Assignment_Attempt.
   * @param {Assignment_AttemptUpsertArgs} args - Arguments to update or create a Assignment_Attempt.
   * @example
   * // Update or create a Assignment_Attempt
   * const assignment_Attempt = await prisma.assignment_Attempt.upsert({
   *   create: {
   *     // ... data to create a Assignment_Attempt
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Assignment_Attempt we want to update
   *   }
   * })
   */
  upsert<T extends Assignment_AttemptUpsertArgs>(args: Prisma.SelectSubset<T, Assignment_AttemptUpsertArgs<ExtArgs>>): Prisma.Prisma__Assignment_AttemptClient<runtime.Types.Result.GetResult<Prisma.$Assignment_AttemptPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Assignment_Attempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptCountArgs} args - Arguments to filter Assignment_Attempts to count.
   * @example
   * // Count the number of Assignment_Attempts
   * const count = await prisma.assignment_Attempt.count({
   *   where: {
   *     // ... the filter for the Assignment_Attempts we want to count
   *   }
   * })
  **/
  count<T extends Assignment_AttemptCountArgs>(
    args?: Prisma.Subset<T, Assignment_AttemptCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Assignment_AttemptCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Assignment_Attempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Assignment_AttemptAggregateArgs>(args: Prisma.Subset<T, Assignment_AttemptAggregateArgs>): Prisma.PrismaPromise<GetAssignment_AttemptAggregateType<T>>

  /**
   * Group by Assignment_Attempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Assignment_AttemptGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Assignment_AttemptGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Assignment_AttemptGroupByArgs['orderBy'] }
      : { orderBy?: Assignment_AttemptGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Assignment_AttemptGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssignment_AttemptGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Assignment_Attempt model
 */
readonly fields: Assignment_AttemptFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Assignment_Attempt.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Assignment_AttemptClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Assignment_Attempt model
 */
export interface Assignment_AttemptFieldRefs {
  readonly id: Prisma.FieldRef<"Assignment_Attempt", 'String'>
  readonly topicId: Prisma.FieldRef<"Assignment_Attempt", 'String'>
  readonly userId: Prisma.FieldRef<"Assignment_Attempt", 'String'>
  readonly percentage: Prisma.FieldRef<"Assignment_Attempt", 'Int'>
  readonly passed: Prisma.FieldRef<"Assignment_Attempt", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Assignment_Attempt", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Assignment_Attempt findUnique
 */
export type Assignment_AttemptFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter, which Assignment_Attempt to fetch.
   */
  where: Prisma.Assignment_AttemptWhereUniqueInput
}

/**
 * Assignment_Attempt findUniqueOrThrow
 */
export type Assignment_AttemptFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter, which Assignment_Attempt to fetch.
   */
  where: Prisma.Assignment_AttemptWhereUniqueInput
}

/**
 * Assignment_Attempt findFirst
 */
export type Assignment_AttemptFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter, which Assignment_Attempt to fetch.
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assignment_Attempts to fetch.
   */
  orderBy?: Prisma.Assignment_AttemptOrderByWithRelationInput | Prisma.Assignment_AttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assignment_Attempts.
   */
  cursor?: Prisma.Assignment_AttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assignment_Attempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assignment_Attempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assignment_Attempts.
   */
  distinct?: Prisma.Assignment_AttemptScalarFieldEnum | Prisma.Assignment_AttemptScalarFieldEnum[]
}

/**
 * Assignment_Attempt findFirstOrThrow
 */
export type Assignment_AttemptFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter, which Assignment_Attempt to fetch.
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assignment_Attempts to fetch.
   */
  orderBy?: Prisma.Assignment_AttemptOrderByWithRelationInput | Prisma.Assignment_AttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assignment_Attempts.
   */
  cursor?: Prisma.Assignment_AttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assignment_Attempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assignment_Attempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assignment_Attempts.
   */
  distinct?: Prisma.Assignment_AttemptScalarFieldEnum | Prisma.Assignment_AttemptScalarFieldEnum[]
}

/**
 * Assignment_Attempt findMany
 */
export type Assignment_AttemptFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter, which Assignment_Attempts to fetch.
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assignment_Attempts to fetch.
   */
  orderBy?: Prisma.Assignment_AttemptOrderByWithRelationInput | Prisma.Assignment_AttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Assignment_Attempts.
   */
  cursor?: Prisma.Assignment_AttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assignment_Attempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assignment_Attempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assignment_Attempts.
   */
  distinct?: Prisma.Assignment_AttemptScalarFieldEnum | Prisma.Assignment_AttemptScalarFieldEnum[]
}

/**
 * Assignment_Attempt create
 */
export type Assignment_AttemptCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * The data needed to create a Assignment_Attempt.
   */
  data: Prisma.XOR<Prisma.Assignment_AttemptCreateInput, Prisma.Assignment_AttemptUncheckedCreateInput>
}

/**
 * Assignment_Attempt createMany
 */
export type Assignment_AttemptCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Assignment_Attempts.
   */
  data: Prisma.Assignment_AttemptCreateManyInput | Prisma.Assignment_AttemptCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Assignment_Attempt createManyAndReturn
 */
export type Assignment_AttemptCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * The data used to create many Assignment_Attempts.
   */
  data: Prisma.Assignment_AttemptCreateManyInput | Prisma.Assignment_AttemptCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Assignment_Attempt update
 */
export type Assignment_AttemptUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * The data needed to update a Assignment_Attempt.
   */
  data: Prisma.XOR<Prisma.Assignment_AttemptUpdateInput, Prisma.Assignment_AttemptUncheckedUpdateInput>
  /**
   * Choose, which Assignment_Attempt to update.
   */
  where: Prisma.Assignment_AttemptWhereUniqueInput
}

/**
 * Assignment_Attempt updateMany
 */
export type Assignment_AttemptUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Assignment_Attempts.
   */
  data: Prisma.XOR<Prisma.Assignment_AttemptUpdateManyMutationInput, Prisma.Assignment_AttemptUncheckedUpdateManyInput>
  /**
   * Filter which Assignment_Attempts to update
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * Limit how many Assignment_Attempts to update.
   */
  limit?: number
}

/**
 * Assignment_Attempt updateManyAndReturn
 */
export type Assignment_AttemptUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * The data used to update Assignment_Attempts.
   */
  data: Prisma.XOR<Prisma.Assignment_AttemptUpdateManyMutationInput, Prisma.Assignment_AttemptUncheckedUpdateManyInput>
  /**
   * Filter which Assignment_Attempts to update
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * Limit how many Assignment_Attempts to update.
   */
  limit?: number
}

/**
 * Assignment_Attempt upsert
 */
export type Assignment_AttemptUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * The filter to search for the Assignment_Attempt to update in case it exists.
   */
  where: Prisma.Assignment_AttemptWhereUniqueInput
  /**
   * In case the Assignment_Attempt found by the `where` argument doesn't exist, create a new Assignment_Attempt with this data.
   */
  create: Prisma.XOR<Prisma.Assignment_AttemptCreateInput, Prisma.Assignment_AttemptUncheckedCreateInput>
  /**
   * In case the Assignment_Attempt was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Assignment_AttemptUpdateInput, Prisma.Assignment_AttemptUncheckedUpdateInput>
}

/**
 * Assignment_Attempt delete
 */
export type Assignment_AttemptDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
  /**
   * Filter which Assignment_Attempt to delete.
   */
  where: Prisma.Assignment_AttemptWhereUniqueInput
}

/**
 * Assignment_Attempt deleteMany
 */
export type Assignment_AttemptDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assignment_Attempts to delete
   */
  where?: Prisma.Assignment_AttemptWhereInput
  /**
   * Limit how many Assignment_Attempts to delete.
   */
  limit?: number
}

/**
 * Assignment_Attempt without action
 */
export type Assignment_AttemptDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assignment_Attempt
   */
  select?: Prisma.Assignment_AttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assignment_Attempt
   */
  omit?: Prisma.Assignment_AttemptOmit<ExtArgs> | null
}
