
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModuleEnrollment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ModuleEnrollment
 * 
 */
export type ModuleEnrollmentModel = runtime.Types.Result.DefaultSelection<Prisma.$ModuleEnrollmentPayload>

export type AggregateModuleEnrollment = {
  _count: ModuleEnrollmentCountAggregateOutputType | null
  _min: ModuleEnrollmentMinAggregateOutputType | null
  _max: ModuleEnrollmentMaxAggregateOutputType | null
}

export type ModuleEnrollmentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  moduleId: string | null
  enrolledAt: Date | null
}

export type ModuleEnrollmentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  moduleId: string | null
  enrolledAt: Date | null
}

export type ModuleEnrollmentCountAggregateOutputType = {
  id: number
  userId: number
  moduleId: number
  enrolledAt: number
  _all: number
}


export type ModuleEnrollmentMinAggregateInputType = {
  id?: true
  userId?: true
  moduleId?: true
  enrolledAt?: true
}

export type ModuleEnrollmentMaxAggregateInputType = {
  id?: true
  userId?: true
  moduleId?: true
  enrolledAt?: true
}

export type ModuleEnrollmentCountAggregateInputType = {
  id?: true
  userId?: true
  moduleId?: true
  enrolledAt?: true
  _all?: true
}

export type ModuleEnrollmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModuleEnrollment to aggregate.
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModuleEnrollments to fetch.
   */
  orderBy?: Prisma.ModuleEnrollmentOrderByWithRelationInput | Prisma.ModuleEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModuleEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModuleEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModuleEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModuleEnrollments
  **/
  _count?: true | ModuleEnrollmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModuleEnrollmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModuleEnrollmentMaxAggregateInputType
}

export type GetModuleEnrollmentAggregateType<T extends ModuleEnrollmentAggregateArgs> = {
      [P in keyof T & keyof AggregateModuleEnrollment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModuleEnrollment[P]>
    : Prisma.GetScalarType<T[P], AggregateModuleEnrollment[P]>
}




export type ModuleEnrollmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModuleEnrollmentWhereInput
  orderBy?: Prisma.ModuleEnrollmentOrderByWithAggregationInput | Prisma.ModuleEnrollmentOrderByWithAggregationInput[]
  by: Prisma.ModuleEnrollmentScalarFieldEnum[] | Prisma.ModuleEnrollmentScalarFieldEnum
  having?: Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModuleEnrollmentCountAggregateInputType | true
  _min?: ModuleEnrollmentMinAggregateInputType
  _max?: ModuleEnrollmentMaxAggregateInputType
}

export type ModuleEnrollmentGroupByOutputType = {
  id: string
  userId: string
  moduleId: string
  enrolledAt: Date
  _count: ModuleEnrollmentCountAggregateOutputType | null
  _min: ModuleEnrollmentMinAggregateOutputType | null
  _max: ModuleEnrollmentMaxAggregateOutputType | null
}

export type GetModuleEnrollmentGroupByPayload<T extends ModuleEnrollmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModuleEnrollmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModuleEnrollmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModuleEnrollmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModuleEnrollmentGroupByOutputType[P]>
      }
    >
  >



export type ModuleEnrollmentWhereInput = {
  AND?: Prisma.ModuleEnrollmentWhereInput | Prisma.ModuleEnrollmentWhereInput[]
  OR?: Prisma.ModuleEnrollmentWhereInput[]
  NOT?: Prisma.ModuleEnrollmentWhereInput | Prisma.ModuleEnrollmentWhereInput[]
  id?: Prisma.StringFilter<"ModuleEnrollment"> | string
  userId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  moduleId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  enrolledAt?: Prisma.DateTimeFilter<"ModuleEnrollment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  module?: Prisma.XOR<Prisma.ModuleScalarRelationFilter, Prisma.ModuleWhereInput>
}

export type ModuleEnrollmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  enrolledAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  module?: Prisma.ModuleOrderByWithRelationInput
}

export type ModuleEnrollmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_moduleId?: Prisma.ModuleEnrollmentUserIdModuleIdCompoundUniqueInput
  AND?: Prisma.ModuleEnrollmentWhereInput | Prisma.ModuleEnrollmentWhereInput[]
  OR?: Prisma.ModuleEnrollmentWhereInput[]
  NOT?: Prisma.ModuleEnrollmentWhereInput | Prisma.ModuleEnrollmentWhereInput[]
  userId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  moduleId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  enrolledAt?: Prisma.DateTimeFilter<"ModuleEnrollment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  module?: Prisma.XOR<Prisma.ModuleScalarRelationFilter, Prisma.ModuleWhereInput>
}, "id" | "userId_moduleId">

export type ModuleEnrollmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  enrolledAt?: Prisma.SortOrder
  _count?: Prisma.ModuleEnrollmentCountOrderByAggregateInput
  _max?: Prisma.ModuleEnrollmentMaxOrderByAggregateInput
  _min?: Prisma.ModuleEnrollmentMinOrderByAggregateInput
}

export type ModuleEnrollmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput | Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput | Prisma.ModuleEnrollmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ModuleEnrollment"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ModuleEnrollment"> | string
  moduleId?: Prisma.StringWithAggregatesFilter<"ModuleEnrollment"> | string
  enrolledAt?: Prisma.DateTimeWithAggregatesFilter<"ModuleEnrollment"> | Date | string
}

export type ModuleEnrollmentCreateInput = {
  id?: string
  enrolledAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutEnrollmentsInput
  module: Prisma.ModuleCreateNestedOneWithoutEnrollmentsInput
}

export type ModuleEnrollmentUncheckedCreateInput = {
  id?: string
  userId: string
  moduleId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutEnrollmentsNestedInput
  module?: Prisma.ModuleUpdateOneRequiredWithoutEnrollmentsNestedInput
}

export type ModuleEnrollmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentCreateManyInput = {
  id?: string
  userId: string
  moduleId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentListRelationFilter = {
  every?: Prisma.ModuleEnrollmentWhereInput
  some?: Prisma.ModuleEnrollmentWhereInput
  none?: Prisma.ModuleEnrollmentWhereInput
}

export type ModuleEnrollmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ModuleEnrollmentUserIdModuleIdCompoundUniqueInput = {
  userId: string
  moduleId: string
}

export type ModuleEnrollmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  enrolledAt?: Prisma.SortOrder
}

export type ModuleEnrollmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  enrolledAt?: Prisma.SortOrder
}

export type ModuleEnrollmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  moduleId?: Prisma.SortOrder
  enrolledAt?: Prisma.SortOrder
}

export type ModuleEnrollmentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput> | Prisma.ModuleEnrollmentCreateWithoutUserInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyUserInputEnvelope
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
}

export type ModuleEnrollmentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput> | Prisma.ModuleEnrollmentCreateWithoutUserInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyUserInputEnvelope
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
}

export type ModuleEnrollmentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput> | Prisma.ModuleEnrollmentCreateWithoutUserInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutUserInput | Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyUserInputEnvelope
  set?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  delete?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  update?: Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutUserInput | Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutUserInput | Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
}

export type ModuleEnrollmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput> | Prisma.ModuleEnrollmentCreateWithoutUserInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutUserInput | Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyUserInputEnvelope
  set?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  delete?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  update?: Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutUserInput | Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutUserInput | Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
}

export type ModuleEnrollmentCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput> | Prisma.ModuleEnrollmentCreateWithoutModuleInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyModuleInputEnvelope
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
}

export type ModuleEnrollmentUncheckedCreateNestedManyWithoutModuleInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput> | Prisma.ModuleEnrollmentCreateWithoutModuleInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyModuleInputEnvelope
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
}

export type ModuleEnrollmentUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput> | Prisma.ModuleEnrollmentCreateWithoutModuleInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutModuleInput | Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyModuleInputEnvelope
  set?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  delete?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  update?: Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutModuleInput | Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutModuleInput | Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
}

export type ModuleEnrollmentUncheckedUpdateManyWithoutModuleNestedInput = {
  create?: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput> | Prisma.ModuleEnrollmentCreateWithoutModuleInput[] | Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput[]
  connectOrCreate?: Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput | Prisma.ModuleEnrollmentCreateOrConnectWithoutModuleInput[]
  upsert?: Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutModuleInput | Prisma.ModuleEnrollmentUpsertWithWhereUniqueWithoutModuleInput[]
  createMany?: Prisma.ModuleEnrollmentCreateManyModuleInputEnvelope
  set?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  delete?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  connect?: Prisma.ModuleEnrollmentWhereUniqueInput | Prisma.ModuleEnrollmentWhereUniqueInput[]
  update?: Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutModuleInput | Prisma.ModuleEnrollmentUpdateWithWhereUniqueWithoutModuleInput[]
  updateMany?: Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutModuleInput | Prisma.ModuleEnrollmentUpdateManyWithWhereWithoutModuleInput[]
  deleteMany?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
}

export type ModuleEnrollmentCreateWithoutUserInput = {
  id?: string
  enrolledAt?: Date | string
  module: Prisma.ModuleCreateNestedOneWithoutEnrollmentsInput
}

export type ModuleEnrollmentUncheckedCreateWithoutUserInput = {
  id?: string
  moduleId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentCreateOrConnectWithoutUserInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput>
}

export type ModuleEnrollmentCreateManyUserInputEnvelope = {
  data: Prisma.ModuleEnrollmentCreateManyUserInput | Prisma.ModuleEnrollmentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ModuleEnrollmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  update: Prisma.XOR<Prisma.ModuleEnrollmentUpdateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutUserInput>
}

export type ModuleEnrollmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateWithoutUserInput, Prisma.ModuleEnrollmentUncheckedUpdateWithoutUserInput>
}

export type ModuleEnrollmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ModuleEnrollmentScalarWhereInput
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateManyMutationInput, Prisma.ModuleEnrollmentUncheckedUpdateManyWithoutUserInput>
}

export type ModuleEnrollmentScalarWhereInput = {
  AND?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
  OR?: Prisma.ModuleEnrollmentScalarWhereInput[]
  NOT?: Prisma.ModuleEnrollmentScalarWhereInput | Prisma.ModuleEnrollmentScalarWhereInput[]
  id?: Prisma.StringFilter<"ModuleEnrollment"> | string
  userId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  moduleId?: Prisma.StringFilter<"ModuleEnrollment"> | string
  enrolledAt?: Prisma.DateTimeFilter<"ModuleEnrollment"> | Date | string
}

export type ModuleEnrollmentCreateWithoutModuleInput = {
  id?: string
  enrolledAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutEnrollmentsInput
}

export type ModuleEnrollmentUncheckedCreateWithoutModuleInput = {
  id?: string
  userId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentCreateOrConnectWithoutModuleInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  create: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput>
}

export type ModuleEnrollmentCreateManyModuleInputEnvelope = {
  data: Prisma.ModuleEnrollmentCreateManyModuleInput | Prisma.ModuleEnrollmentCreateManyModuleInput[]
  skipDuplicates?: boolean
}

export type ModuleEnrollmentUpsertWithWhereUniqueWithoutModuleInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  update: Prisma.XOR<Prisma.ModuleEnrollmentUpdateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedUpdateWithoutModuleInput>
  create: Prisma.XOR<Prisma.ModuleEnrollmentCreateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedCreateWithoutModuleInput>
}

export type ModuleEnrollmentUpdateWithWhereUniqueWithoutModuleInput = {
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateWithoutModuleInput, Prisma.ModuleEnrollmentUncheckedUpdateWithoutModuleInput>
}

export type ModuleEnrollmentUpdateManyWithWhereWithoutModuleInput = {
  where: Prisma.ModuleEnrollmentScalarWhereInput
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateManyMutationInput, Prisma.ModuleEnrollmentUncheckedUpdateManyWithoutModuleInput>
}

export type ModuleEnrollmentCreateManyUserInput = {
  id?: string
  moduleId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  module?: Prisma.ModuleUpdateOneRequiredWithoutEnrollmentsNestedInput
}

export type ModuleEnrollmentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  moduleId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentCreateManyModuleInput = {
  id?: string
  userId: string
  enrolledAt?: Date | string
}

export type ModuleEnrollmentUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutEnrollmentsNestedInput
}

export type ModuleEnrollmentUncheckedUpdateWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModuleEnrollmentUncheckedUpdateManyWithoutModuleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enrolledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ModuleEnrollmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  moduleId?: boolean
  enrolledAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moduleEnrollment"]>

export type ModuleEnrollmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  moduleId?: boolean
  enrolledAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moduleEnrollment"]>

export type ModuleEnrollmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  moduleId?: boolean
  enrolledAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moduleEnrollment"]>

export type ModuleEnrollmentSelectScalar = {
  id?: boolean
  userId?: boolean
  moduleId?: boolean
  enrolledAt?: boolean
}

export type ModuleEnrollmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "moduleId" | "enrolledAt", ExtArgs["result"]["moduleEnrollment"]>
export type ModuleEnrollmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}
export type ModuleEnrollmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}
export type ModuleEnrollmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  module?: boolean | Prisma.ModuleDefaultArgs<ExtArgs>
}

export type $ModuleEnrollmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModuleEnrollment"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    module: Prisma.$ModulePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    moduleId: string
    enrolledAt: Date
  }, ExtArgs["result"]["moduleEnrollment"]>
  composites: {}
}

export type ModuleEnrollmentGetPayload<S extends boolean | null | undefined | ModuleEnrollmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload, S>

export type ModuleEnrollmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModuleEnrollmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModuleEnrollmentCountAggregateInputType | true
  }

export interface ModuleEnrollmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModuleEnrollment'], meta: { name: 'ModuleEnrollment' } }
  /**
   * Find zero or one ModuleEnrollment that matches the filter.
   * @param {ModuleEnrollmentFindUniqueArgs} args - Arguments to find a ModuleEnrollment
   * @example
   * // Get one ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModuleEnrollmentFindUniqueArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModuleEnrollment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModuleEnrollmentFindUniqueOrThrowArgs} args - Arguments to find a ModuleEnrollment
   * @example
   * // Get one ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModuleEnrollmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModuleEnrollment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentFindFirstArgs} args - Arguments to find a ModuleEnrollment
   * @example
   * // Get one ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModuleEnrollmentFindFirstArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModuleEnrollment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentFindFirstOrThrowArgs} args - Arguments to find a ModuleEnrollment
   * @example
   * // Get one ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModuleEnrollmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModuleEnrollments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModuleEnrollments
   * const moduleEnrollments = await prisma.moduleEnrollment.findMany()
   * 
   * // Get first 10 ModuleEnrollments
   * const moduleEnrollments = await prisma.moduleEnrollment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const moduleEnrollmentWithIdOnly = await prisma.moduleEnrollment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModuleEnrollmentFindManyArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModuleEnrollment.
   * @param {ModuleEnrollmentCreateArgs} args - Arguments to create a ModuleEnrollment.
   * @example
   * // Create one ModuleEnrollment
   * const ModuleEnrollment = await prisma.moduleEnrollment.create({
   *   data: {
   *     // ... data to create a ModuleEnrollment
   *   }
   * })
   * 
   */
  create<T extends ModuleEnrollmentCreateArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentCreateArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModuleEnrollments.
   * @param {ModuleEnrollmentCreateManyArgs} args - Arguments to create many ModuleEnrollments.
   * @example
   * // Create many ModuleEnrollments
   * const moduleEnrollment = await prisma.moduleEnrollment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModuleEnrollmentCreateManyArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModuleEnrollments and returns the data saved in the database.
   * @param {ModuleEnrollmentCreateManyAndReturnArgs} args - Arguments to create many ModuleEnrollments.
   * @example
   * // Create many ModuleEnrollments
   * const moduleEnrollment = await prisma.moduleEnrollment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModuleEnrollments and only return the `id`
   * const moduleEnrollmentWithIdOnly = await prisma.moduleEnrollment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModuleEnrollmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModuleEnrollment.
   * @param {ModuleEnrollmentDeleteArgs} args - Arguments to delete one ModuleEnrollment.
   * @example
   * // Delete one ModuleEnrollment
   * const ModuleEnrollment = await prisma.moduleEnrollment.delete({
   *   where: {
   *     // ... filter to delete one ModuleEnrollment
   *   }
   * })
   * 
   */
  delete<T extends ModuleEnrollmentDeleteArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentDeleteArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModuleEnrollment.
   * @param {ModuleEnrollmentUpdateArgs} args - Arguments to update one ModuleEnrollment.
   * @example
   * // Update one ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModuleEnrollmentUpdateArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentUpdateArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModuleEnrollments.
   * @param {ModuleEnrollmentDeleteManyArgs} args - Arguments to filter ModuleEnrollments to delete.
   * @example
   * // Delete a few ModuleEnrollments
   * const { count } = await prisma.moduleEnrollment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModuleEnrollmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModuleEnrollmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModuleEnrollments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModuleEnrollments
   * const moduleEnrollment = await prisma.moduleEnrollment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModuleEnrollmentUpdateManyArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModuleEnrollments and returns the data updated in the database.
   * @param {ModuleEnrollmentUpdateManyAndReturnArgs} args - Arguments to update many ModuleEnrollments.
   * @example
   * // Update many ModuleEnrollments
   * const moduleEnrollment = await prisma.moduleEnrollment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModuleEnrollments and only return the `id`
   * const moduleEnrollmentWithIdOnly = await prisma.moduleEnrollment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModuleEnrollmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModuleEnrollment.
   * @param {ModuleEnrollmentUpsertArgs} args - Arguments to update or create a ModuleEnrollment.
   * @example
   * // Update or create a ModuleEnrollment
   * const moduleEnrollment = await prisma.moduleEnrollment.upsert({
   *   create: {
   *     // ... data to create a ModuleEnrollment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModuleEnrollment we want to update
   *   }
   * })
   */
  upsert<T extends ModuleEnrollmentUpsertArgs>(args: Prisma.SelectSubset<T, ModuleEnrollmentUpsertArgs<ExtArgs>>): Prisma.Prisma__ModuleEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$ModuleEnrollmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModuleEnrollments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentCountArgs} args - Arguments to filter ModuleEnrollments to count.
   * @example
   * // Count the number of ModuleEnrollments
   * const count = await prisma.moduleEnrollment.count({
   *   where: {
   *     // ... the filter for the ModuleEnrollments we want to count
   *   }
   * })
  **/
  count<T extends ModuleEnrollmentCountArgs>(
    args?: Prisma.Subset<T, ModuleEnrollmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModuleEnrollmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModuleEnrollment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModuleEnrollmentAggregateArgs>(args: Prisma.Subset<T, ModuleEnrollmentAggregateArgs>): Prisma.PrismaPromise<GetModuleEnrollmentAggregateType<T>>

  /**
   * Group by ModuleEnrollment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModuleEnrollmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModuleEnrollmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModuleEnrollmentGroupByArgs['orderBy'] }
      : { orderBy?: ModuleEnrollmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModuleEnrollmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModuleEnrollmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModuleEnrollment model
 */
readonly fields: ModuleEnrollmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModuleEnrollment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModuleEnrollmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  module<T extends Prisma.ModuleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModuleDefaultArgs<ExtArgs>>): Prisma.Prisma__ModuleClient<runtime.Types.Result.GetResult<Prisma.$ModulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModuleEnrollment model
 */
export interface ModuleEnrollmentFieldRefs {
  readonly id: Prisma.FieldRef<"ModuleEnrollment", 'String'>
  readonly userId: Prisma.FieldRef<"ModuleEnrollment", 'String'>
  readonly moduleId: Prisma.FieldRef<"ModuleEnrollment", 'String'>
  readonly enrolledAt: Prisma.FieldRef<"ModuleEnrollment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ModuleEnrollment findUnique
 */
export type ModuleEnrollmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which ModuleEnrollment to fetch.
   */
  where: Prisma.ModuleEnrollmentWhereUniqueInput
}

/**
 * ModuleEnrollment findUniqueOrThrow
 */
export type ModuleEnrollmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which ModuleEnrollment to fetch.
   */
  where: Prisma.ModuleEnrollmentWhereUniqueInput
}

/**
 * ModuleEnrollment findFirst
 */
export type ModuleEnrollmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which ModuleEnrollment to fetch.
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModuleEnrollments to fetch.
   */
  orderBy?: Prisma.ModuleEnrollmentOrderByWithRelationInput | Prisma.ModuleEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModuleEnrollments.
   */
  cursor?: Prisma.ModuleEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModuleEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModuleEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModuleEnrollments.
   */
  distinct?: Prisma.ModuleEnrollmentScalarFieldEnum | Prisma.ModuleEnrollmentScalarFieldEnum[]
}

/**
 * ModuleEnrollment findFirstOrThrow
 */
export type ModuleEnrollmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which ModuleEnrollment to fetch.
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModuleEnrollments to fetch.
   */
  orderBy?: Prisma.ModuleEnrollmentOrderByWithRelationInput | Prisma.ModuleEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModuleEnrollments.
   */
  cursor?: Prisma.ModuleEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModuleEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModuleEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModuleEnrollments.
   */
  distinct?: Prisma.ModuleEnrollmentScalarFieldEnum | Prisma.ModuleEnrollmentScalarFieldEnum[]
}

/**
 * ModuleEnrollment findMany
 */
export type ModuleEnrollmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which ModuleEnrollments to fetch.
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModuleEnrollments to fetch.
   */
  orderBy?: Prisma.ModuleEnrollmentOrderByWithRelationInput | Prisma.ModuleEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModuleEnrollments.
   */
  cursor?: Prisma.ModuleEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModuleEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModuleEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModuleEnrollments.
   */
  distinct?: Prisma.ModuleEnrollmentScalarFieldEnum | Prisma.ModuleEnrollmentScalarFieldEnum[]
}

/**
 * ModuleEnrollment create
 */
export type ModuleEnrollmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * The data needed to create a ModuleEnrollment.
   */
  data: Prisma.XOR<Prisma.ModuleEnrollmentCreateInput, Prisma.ModuleEnrollmentUncheckedCreateInput>
}

/**
 * ModuleEnrollment createMany
 */
export type ModuleEnrollmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModuleEnrollments.
   */
  data: Prisma.ModuleEnrollmentCreateManyInput | Prisma.ModuleEnrollmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModuleEnrollment createManyAndReturn
 */
export type ModuleEnrollmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * The data used to create many ModuleEnrollments.
   */
  data: Prisma.ModuleEnrollmentCreateManyInput | Prisma.ModuleEnrollmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModuleEnrollment update
 */
export type ModuleEnrollmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * The data needed to update a ModuleEnrollment.
   */
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateInput, Prisma.ModuleEnrollmentUncheckedUpdateInput>
  /**
   * Choose, which ModuleEnrollment to update.
   */
  where: Prisma.ModuleEnrollmentWhereUniqueInput
}

/**
 * ModuleEnrollment updateMany
 */
export type ModuleEnrollmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModuleEnrollments.
   */
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateManyMutationInput, Prisma.ModuleEnrollmentUncheckedUpdateManyInput>
  /**
   * Filter which ModuleEnrollments to update
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * Limit how many ModuleEnrollments to update.
   */
  limit?: number
}

/**
 * ModuleEnrollment updateManyAndReturn
 */
export type ModuleEnrollmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * The data used to update ModuleEnrollments.
   */
  data: Prisma.XOR<Prisma.ModuleEnrollmentUpdateManyMutationInput, Prisma.ModuleEnrollmentUncheckedUpdateManyInput>
  /**
   * Filter which ModuleEnrollments to update
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * Limit how many ModuleEnrollments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModuleEnrollment upsert
 */
export type ModuleEnrollmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * The filter to search for the ModuleEnrollment to update in case it exists.
   */
  where: Prisma.ModuleEnrollmentWhereUniqueInput
  /**
   * In case the ModuleEnrollment found by the `where` argument doesn't exist, create a new ModuleEnrollment with this data.
   */
  create: Prisma.XOR<Prisma.ModuleEnrollmentCreateInput, Prisma.ModuleEnrollmentUncheckedCreateInput>
  /**
   * In case the ModuleEnrollment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModuleEnrollmentUpdateInput, Prisma.ModuleEnrollmentUncheckedUpdateInput>
}

/**
 * ModuleEnrollment delete
 */
export type ModuleEnrollmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
  /**
   * Filter which ModuleEnrollment to delete.
   */
  where: Prisma.ModuleEnrollmentWhereUniqueInput
}

/**
 * ModuleEnrollment deleteMany
 */
export type ModuleEnrollmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModuleEnrollments to delete
   */
  where?: Prisma.ModuleEnrollmentWhereInput
  /**
   * Limit how many ModuleEnrollments to delete.
   */
  limit?: number
}

/**
 * ModuleEnrollment without action
 */
export type ModuleEnrollmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModuleEnrollment
   */
  select?: Prisma.ModuleEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModuleEnrollment
   */
  omit?: Prisma.ModuleEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModuleEnrollmentInclude<ExtArgs> | null
}
